# Render Configuration for ChartMaster Backend

services:
  - type: web
    name: chartmaster-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        fromDatabase:
          name: chartmaster-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRE
        value: 30d

databases:
  - name: chartmaster-db
    databaseName: chartmaster
    plan: free
